export enum SCREEN_NAME {
  SPLASH = "SPLASH",
  MAIN = "MAIN",

  POKEMONS = "POKEMONS",

  POKEMON_INFO = "POKEMON_INFO",

  MOVES = "MOVES",
  MOVE_INFO = "MOVE_INFO",

  ITEMS = "ITEMS",

  TYPES = "TYPES",
  TYPE_INFO = "TYPE_INFO",
}
